# Generated by Django 5.2.3 on 2025-06-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_itinerary_destination_itinerary_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
